#!/Users/kiharakeito/.rbenv/shims/ruby
require 'date'
require 'optparse'

# 表示させる月と年指定(初期設定：今月表示)
month =  Date.today.month
year = Date.today.year

# オプション指定の処理
month_range_start = 1
month_range_end = 12
year_range_start = 1970
year_range_end = 2100

begin
  options = ARGV.getopts("m:y:")
  if options["m"] #月指定がある場合
    if options["m"].to_i >= month_range_start && options["m"].to_i <= month_range_end #月指定数値判定
      month = options["m"].to_i #月指定(オプション設定)
    else
      puts "月指定は、1〜12の間の数字で指定してください。"
      return
    end
  end
  if options["y"] #年指定がある場合
    if options["y"].to_i >= year_range_start && options["y"].to_i <= year_range_end #年指定数値判定
      year = options["y"].to_i #年指定(オプション設定)
    else
      puts "年指定は、1970〜2100の間の数字で指定してください。"
      return
    end
  end
rescue => e
  puts "例外が発生しました: #{e.message}"
  return
end

# カレンダーの月・年と曜日表示
puts "      #{month}月 #{year}"
puts "日 月 火 水 木 金 土"

# カレンダー日にち表示
month_days = Date.new(year, month, -1).day #指定月は何日あるか取得
month_days.times do |day_counter| #日数分繰り返し
  day_counter += 1
  day_display = day_counter.to_s + " " #すべての日付右にスペース追加
  day_display = " " + day_display if day_counter.to_s.size == 1 #日付1桁の場合左にスペース追加
  day_of_week = Date.new(year, month, day_counter).wday #曜日取得
  if day_counter == 1 #1日の場合の曜日位置移動（スペース追加）
    day_of_week.times do |x|
      day_display = "   " + day_display
    end
  end
  day_display = day_display + "\n" if day_of_week == 6 #土曜日の場合改行追加
  print day_display
end
